epam/aws-syndicate

plugin/deployment-configuration-annotations/pom.xml, plugin/deployment-configuration-maven-plugin/pom.xml, plugin/pom.xml
Added maven `release` profile. Updated version of artifacts to 1.2.0.
=> Add config for maven deploy stage

examples/demo-project/demo-java/pom.xml, plugin/deployment-configuration-annotations/pom.xml, plugin/deployment-configuration-maven-plugin/pom.xml
…t-configuration-maven-plugin to 1.4.0; edit syndicate-demo example to use tf goal
=> Update example, update versions

syndicate/connection/api_gateway_connection.py, syndicate/core/build/deployment_processor.py, syndicate/core/resources/api_gateway_resource.py, syndicate/core/resources/lambda_resource.py
Comment update_gateway_reponses method call due to botocore's InternalFailure while performing it
=> Customize gateway responses invocations skip

syndicate/connection/lambda_connection.py
=> #52 fix update lambdas flow with no vpc configuration specified

requirements.txt, samples/sample-config/sdct.conf, samples/sample-python-project/deployment_resources.json, samples/sample-python-project/lambdas/api-handler/lambda_config.json, samples/sample-python-project/lambdas/job-processor/handler.py, samples/sample-python-project/lambdas/job-processor/lambda_config.json, samples/sample-python-project/lambdas/job-validator/deployment_resources.json, samples/sample-python-project/lambdas/job-validator/handler.py, samples/sample-python-project/lambdas/job-validator/lambda_config.json, samples/sample-python-project/models/Job.py, samples/sample-python-project/requirements.txt, syndicate/connection/lambda_connection.py, syndicate/core/resources/helper.py, syndicate/core/resources/iam_resource.py, syndicate/core/resources/lambda_resource.py
Implementation of #57 
1. edit sdct_conf;
2. deploy sample python project;
3. check AWS console if lambdas configurations correspond to meta;
4. update concurrency in lambda_config.json files with new values; 
5. update sample application;
6. repeat step 3
7. clean sample application infra.
=> Lambda provisioned concurrency

plugin/deployment-configuration-annotations/pom.xml, plugin/deployment-configuration-maven-plugin/pom.xml, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/goal/AbstractMetaGoal.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/goal/GenerateDynamoDbSchemesGoal.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/goal/SyndicateMetaGeneratorGoal.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/model/JsonSchema.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/model/JsonType.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/processor/AbstractAnnotationProcessor.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/processor/impl/DynamoDBDocumentAnnotationProcessor.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/processor/impl/LambdaHandlerAnnotationProcessor.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/processor/impl/LayerAnnotationProcessor.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/resolvers/credentials/AbstractChainedCredentialResolver.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/resolvers/credentials/CredentialResolverChain.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/resolvers/credentials/IChainedCredentialsResolver.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/resolvers/credentials/impl/CliParametersCredentialResolver.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/resolvers/credentials/impl/EnvironmentPropertiesCredentialsResolver.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/resolvers/reflection/AttributeNameChainedResolver.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/resolvers/reflection/IChainedResolver.java, plugin/deployment-configuration-maven-plugin/src/test/java/com/syndicate/deployment/fail/GenerateJsonSchemaMojoFailTest.java, plugin/deployment-configuration-maven-plugin/src/test/java/com/syndicate/deployment/fail/GenerateLambdaConfigMojoFailTest.java, plugin/deployment-configuration-maven-plugin/src/test/java/com/syndicate/deployment/success/GenerateJsonSchemaMojoSuccessTest.java, plugin/deployment-configuration-maven-plugin/src/test/java/com/syndicate/deployment/success/GenerateLambdaConfigMojoSuccessTest.java, plugin/deployment-configuration-maven-plugin/src/test/java/com/syndicate/deployment/success/dynamodb/TestTable.java, plugin/deployment-configuration-maven-plugin/src/test/java/com/syndicate/deployment/success/dynamodb/TestTableChild.java, plugin/deployment-configuration-maven-plugin/src/test/resources/plugin-config-dynamodb-goal.xml, plugin/pom.xml
=> jsonschema-generating

CHANGELOG.md, setup.py, syndicate/core/build/validator/dynamodb_validator.py, syndicate/core/resources/cloud_watch_resource.py, syndicate/core/resources/resources_provider.py
=> fix LSI validation, CloudWatch Events deployment

requirements.txt
Updated file as required in https://pip.pypa.io/en/stable/reference/pip_install/#requirements-file-format
=> Update Requirements File Format

syndicate/core/generators/contents.py, syndicate/core/generators/lambda_function.py, syndicate/core/generators/project.py, syndicate/core/groups/__init__.py, syndicate/core/groups/generate.py, syndicate/core/project_state.py
Improved generate project command
=> Improved generate project command

CHANGELOG.md, syndicate/core/handlers.py
=> Implemented test command

CHANGELOG.md, syndicate/core/handlers.py
=> Improve generate lambda

syndicate/connection/cognito_identity_provider_connection.py, syndicate/core/resources/cognito_user_pool_resource.py, syndicate/core/resources/helper.py
Fix resolving "auto_verified_attributes" and "username_attributes" in Cognito deployment_resource. Add "sms_configuration" dep. res. parameter which must contain sns_caller_arn in case "phone_number" is given to "auto_verified_attributes".
=> Fix cognito issues

syndicate/core/resources/ec2_resource.py
=> Fix an issue with cleaning ec2 instances

syndicate/core/resources/cloud_watch_alarm_resource.py
The same kind of issue as it was with EC2 instances removing
=> Fix removing cloudwatch alarms

syndicate/core/groups/generate.py, syndicate/core/helper.py
=> Add lambda's name validation

CHANGELOG.md, syndicate/core/generators/contents.py, syndicate/core/generators/lambda_function.py, syndicate/core/generators/tests.py, syndicate/core/handlers.py
Added basic stub tests generation and make 'syndicate test' command execute them from the project's path.
=> Basic stub tests generation

README.md
Changed `syndicate init` to `syndicate generate lambda/config/project`. Updated test deployment. Removed Apache Maven version number (links refer to the latest version).
Not closing issue because additional edits to the README.md are possible.
=> Update README.md for 1.0.0

syndicate/connection/__init__.py, syndicate/connection/resource_groups_tagging_api_connection.py, syndicate/core/build/deployment_processor.py, syndicate/core/conf/processor.py, syndicate/core/conf/validator.py, syndicate/core/groups/meta.py, syndicate/core/groups/tags.py, syndicate/core/handlers.py, syndicate/core/resources/docdb_cluster_resource.py, syndicate/core/resources/docdb_instance_resource.py, syndicate/core/resources/group_tagging_api_resource.py, syndicate/core/resources/resources_provider.py
Specify some common tags in the Syndicate config the following way:
and these tags will be assigned to all the deployed resources
Also you can use cli commands: 
* "syndicate tags apply" -  to apply all the tags from the config to deployed resources;
* "syndicate tags remove" - to remove specified in the config tags from deployed resources;
=> Add common tags

README.md, docs/wiki_syndicate.yml.md, syndicate/core/conf/generator.py, syndicate/core/conf/validator.py, syndicate/core/groups/generate.py, syndicate/core/helper.py
Fixed config validator, added new parameter to 'syndicate generate config' and so forth
=> Add params to generate config

syndicate/core/conf/validator.py, syndicate/core/groups/generate.py, syndicate/core/groups/meta.py, syndicate/core/handlers.py, syndicate/core/helper.py
- added description for each parameter
- updated parameters types
- marked required parameters 
- added aliases
- replaced `check_required_param` function with `required=True` parameter
Closes #180
=> [Documentation] Update commands 

syndicate/core/build/runtime/python.py, syndicate/core/generators/contents.py
**IMPORTANT:**
[This](https://github.com/epam/aws-syndicate/tree/fix-bug-with-lambda-package-folder) branch, which partly solves the issue I described [here](https://github.com/epam/aws-syndicate/issues/143) some time ago, was **MERGED** in the current (thin-lambdas-artifacts) branch before making changes. I did it because the changes from the mentioned branch concerned the current task. First off I suggest checking out the explanation of the [issue](https://github.com/epam/aws-syndicate/issues/143).
The current solution makes this:
=> Thin lambdas artifacts

syndicate/core/conf/processor.py
=> Add support yaml and yml to syndicate config and syndicate aliases

syndicate/core/build/deployment_processor.py, syndicate/core/resources/lambda_resource.py
The following request contains code, that alters the following behaviour.
The fix connotes reordering of the name resolution action, of the meta file, and filtering which occurs when one wishes to provide respective flags, such as `--update_only_types` and `--update_only_resources`.
=> Job Definition Update action fix

syndicate/connection/dax_connection.py, syndicate/core/build/validator/dynamodb_validator.py, syndicate/core/conf/validator.py, syndicate/core/resources/dax_resource.py
=> Dax subnet group adjustment

syndicate/connection/dynamo_connection.py, syndicate/core/resources/dynamo_db_resource.py
=> Add an ability to deploy dynamos with on-demand mode

syndicate/core/resources/lambda_resource.py
The following request, provides a fix for redundant lambda target assignment, by verifying whether the respective event rule contains _arn_ of a lambda to create.
=> Fix redundant event-rule targets

syndicate/core/__init__.py, syndicate/core/handlers.py, syndicate/core/helper.py
Request provides behaviour, which mandates user invoked interruptions, by managing project state in the following manner. At any point of time, given the interruption has been raised and the any lock has been acquired - the aforementioned lock is released and the state is synchronized.
=> Interruption handling

syndicate/core/build/deployment_processor.py, syndicate/core/handlers.py, syndicate/core/resources/batch_compenv_resource.py
Fixes unresolvable key reference during the `remove_deployment_resources` action. May require to be refactored to provide a more flexible approach to execute the flow.
=> Fix key reference issue

syndicate/core/generators/lambda_function.py, syndicate/core/groups/__init__.py, syndicate/core/handlers.py, syndicate/core/helper.py, syndicate/core/project_state/project_state.py
Provided lambda state refreshment, which references retained lambdas inside the project structure. Thus, providing consistency which is enforced before each `assemble` action.
=> Lambda State Consistency

syndicate/core/resources/lambda_resource.py
Provides event sources trigger creation during lambda update action.
=> Lambda Update: event sources

syndicate/connection/lambda_connection.py, syndicate/core/resources/api_gateway_resource.py, syndicate/core/resources/lambda_resource.py
Provides Lambda Resource Based Permission attachment, based on wildcards for resources and methods.
=> Lambda Resource Based Permission attachment 

syndicate/connection/iam_connection.py, syndicate/connection/lambda_connection.py, syndicate/core/resources/helper.py, syndicate/core/resources/lambda_resource.py
=> Do not update vpc config and other params if they have not changed

CHANGELOG.md, syndicate/core/build/artifact_processor.py, syndicate/core/build/meta_processor.py, syndicate/core/build/runtime/python.py, syndicate/core/constants.py, syndicate/core/helper.py
=> Add lambda layer building capabilities

syndicate/connection/iam_connection.py, syndicate/core/transform/build_meta_transformer.py, syndicate/core/transform/cloudformation/converter/cf_api_gateway_converter.py
=> Fix issues in transform command

syndicate/connection/iam_connection.py, syndicate/connection/lambda_connection.py, syndicate/core/build/deployment_processor.py, syndicate/core/helper.py
=> Post merge conflict fixes

CHANGELOG.md, README.md, setup.py, syndicate/core/build/meta_processor.py
Adding support python 3.10 and python 3.11
=> Add support python 3.10 and python 3.11

CHANGELOG.md, setup.py, syndicate/connection/api_gateway_connection.py, syndicate/core/resources/api_gateway_resource.py
Fixed ignored request parameters when creating api gateway's resource method using lambda integration
=> fix ignored request parameters

CHANGELOG.md, setup.py, syndicate/core/build/runtime/python.py
replace ignored pip install parameter `--python` with `python-version`
=> replace ignored pip install parameter `--python` with `python-version`

CHANGELOG.md, plugin/deployment-configuration-maven-plugin/pom.xml, setup.py, syndicate/core/build/meta_processor.py, syndicate/core/conf/generator.py, syndicate/core/conf/processor.py, syndicate/core/conf/validator.py, syndicate/core/groups/generate.py, syndicate/core/helper.py
Implemented extended prefix mode
=> [5300] Feature/extended prefix

CHANGELOG.md, setup.py, syndicate/connection/iam_connection.py, syndicate/core/resources/iam_resource.py
- Added waiting for IAM role creation
- Added time delay after attaching a policy to IAM role
=> Syndicate. Add time delay after on IAM roles deployment.

CHANGELOG.md, setup.py, syndicate/core/build/meta_processor.py
Fixed lambda(with Python runtime) deployment in extended prefix mode
=> Fixed lambda(with Python runtime) deployment in extended prefix mode

CHANGELOG.md, setup.py, syndicate/connection/dynamo_connection.py, syndicate/connection/s3_connection.py
Implemented aws-syndicate s3 lifecycle policy deployment.
=> S3 lifecycle policies

CHANGELOG.md, examples/java/demo-layer-url/jsrc/main/java/com/aws/lambda/handler/HelloHandler.java, plugin/deployment-configuration-annotations/src/main/java/com/syndicate/deployment/annotations/lambda/LambdaLayer.java, plugin/deployment-configuration-annotations/src/main/java/com/syndicate/deployment/model/LayerConfiguration.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/factories/LayerConfigurationFactory.java
This adds lambda layer architecture support to the Java plugin
=> add lambda layers architectures support to Java plugin

CHANGELOG.md, syndicate/core/generators/contents.py
This adds missed import into the Java lambda template
=> add missed import into the Java lambda template

CHANGELOG.md, syndicate/core/helper.py
- syndicate generate config: validate composite deploy_target_bucket (bucket+prefix)
=> validate composite deploy_target_bucket

CHANGELOG.md, setup.py, syndicate/core/build/meta_processor.py
- Refactor handling of duplicate resources for method `_check_duplicated_resources`
=> Refactor handling of duplicate

CHANGELOG.md, setup.py, syndicate/core/resources/api_gateway_resource.py
Fix lambda authorization permissions
=> Fix lambda authorization permissions

CHANGELOG.md, setup.py, syndicate/connection/cognito_identity_provider_connection.py, syndicate/core/export/__init__.py, syndicate/core/export/configuration_exporter.py, syndicate/core/export/export_processor.py, syndicate/core/resources/api_gateway_resource.py, syndicate/core/resources/cognito_user_pool_resource.py
Implemented Cognito User Pools ARNs resolving for OpenAPI specification via the key `x-syndicate-cognito-userpool-names` of the `x-amazon-apigateway-authorizer` extension
=> Resolving ARNs of cognito user pools

CHANGELOG.md, setup.py, syndicate/core/constants.py, syndicate/core/generators/contents.py, syndicate/core/generators/lambda_function.py, syndicate/core/groups/__init__.py, syndicate/core/groups/generate.py, syndicate/core/handlers.py, syndicate/core/helper.py
- Fixed displaying help messages without configured SDCT_CONF environment variable
- Implemented generation of lambda layer meta, the command `syndicate generate lambda_layer`
=> Lambda layer meta generation

CHANGELOG.md, setup.py, syndicate/core/build/meta_processor.py, syndicate/core/build/runtime/swagger_ui.py, syndicate/core/conf/generator.py, syndicate/core/constants.py, syndicate/core/generators/contents.py, syndicate/core/generators/swagger_ui.py, syndicate/core/groups/generate.py
- Added a possibility of usage relative path to swagger_ui OpenAPI specification file
=> Added a possibility of usage relative path to swagger_ui OpenAPI spec

CHANGELOG.md, setup.py
version and changelog adjusted to release
=> version and changelog adjusted to release

CHANGELOG.md, plugin/pom.xml, setup.py
This removes extra dependencies from the Java plugin
=> remove redundant dependencies from the Java plugin

CHANGELOG.md, setup.py, syndicate/connection/api_gateway_connection.py, syndicate/connection/application_autoscaling_connection.py, syndicate/connection/batch_connection.py, syndicate/connection/cloud_watch_connection.py, syndicate/connection/cloudfront_connection.py, syndicate/connection/cognito_identity_connection.py, syndicate/connection/cognito_identity_provider_connection.py, syndicate/connection/dax_connection.py, syndicate/connection/documentdb_connection.py, syndicate/connection/dynamo_connection.py, syndicate/connection/ec2_connection.py, syndicate/connection/elastic_beanstalk_connection.py, syndicate/connection/eventbridge_scheduler_connection.py, syndicate/connection/firehose_connection.py, syndicate/connection/helper.py, syndicate/connection/iam_connection.py, syndicate/connection/kinesis_connection.py, syndicate/connection/kms_connection.py, syndicate/connection/lambda_connection.py, syndicate/connection/s3_connection.py, syndicate/connection/ses_connection.py, syndicate/connection/sns_connection.py, syndicate/connection/sqs_connection.py, syndicate/connection/step_functions_connection.py, syndicate/connection/sts_connection.py, syndicate/core/resources/dax_resource.py, syndicate/core/resources/iam_resource.py, syndicate/core/resources/lambda_resource.py
Implemented subnet group deletion with deletion of the related DAX if the syndicate deployed it
=> Implemented subnet group deletion with deletion of the related DAX

CHANGELOG.md, setup.py, syndicate/core/groups/generate.py, syndicate/core/groups/meta.py, syndicate/core/groups/tags.py, syndicate/core/handlers.py, syndicate/core/helper.py
Added verbose mode for commands `build, deploy, update, clean` by using the flag `--verbose|-v`
=> Added verbose mode for commands `build, deploy, update, clean`

CHANGELOG.md, setup.py, syndicate/core/resources/api_gateway_resource.py
Fixed an error in case of an attempt to delete a nonexistent API Gateway
=> Fixed an error in case of an attempt to delete a nonexistent API Gateway

CHANGELOG.md, syndicate/connection/iam_connection.py, syndicate/connection/sns_connection.py
- Fixed an error in case of an attempt to delete a nonexistent IAM Policy
- Fixed an error in case of an attempt to delete a nonexistent SNS Topic
=> Fixed an error in case of an attempt to delete a nonexistent IAM policy and SNS topic

CHANGELOG.md, syndicate/connection/helper.py
Fixed an error related to `UpdateEventSourceMapping operation` during SQS trigger deployment
=> Fixed an error related to `UpdateEventSourceMapping operation`

.github/workflows/ci-java.yml, .github/workflows/maven.yml, .github/workflows/pypi-package.yml
Added the ability to publish AWS-Syndicate Java plugins to Maven Central
=> Added the ability to publish AWS-Syndicate Java plugins to Maven Central

CHANGELOG.md, syndicate/core/export/configuration_exporter.py
Fixed an error related to export OpenAPI specification in extended prefix mode
=> Fixed an error related to export OpenAPI specification

CHANGELOG.md, setup.py, syndicate/connection/api_gateway_connection.py, syndicate/core/resources/api_gateway_resource.py
- Added support of custom authorizer names in Open API specification security schemes
- Fixed quietness of errors while deploying/updating API Gateway via OpenAPI specification
=> Fix oas dependence from the key authorizer

CHANGELOG.md, setup.py, syndicate/connection/api_gateway_connection.py, syndicate/core/resources/api_gateway_resource.py
Fixed API GW deletion when openapi specification is invalid
=> Fix API GW deletion

CHANGELOG.md, setup.py, syndicate/core/groups/meta.py, syndicate/core/helper.py
Fixed issue with the command 'generate meta api_gateway_resource'
=> Fix generate meta api gateway resource command

CHANGELOG.md, setup.py, syndicate/core/build/meta_processor.py
Fixed an issue related to ARNs resolving in case of empty resource name
=> Fixed an issue related to ARNs resolving in case of empty resource name

CHANGELOG.md, setup.py, syndicate/core/build/deployment_processor.py, syndicate/core/handlers.py
Fixed an issue related to improper filtering of resources in case of different types of filter usage
=> Fixed an issue related to improper filtering of resources

CHANGELOG.md, requirements.txt, setup.py, syndicate/core/build/runtime/nodejs.py, syndicate/core/build/runtime/python.py
=> Added support of Python 3.12

CHANGELOG.md, syndicate/connection/sqs_connection.py, syndicate/core/resources/sqs_resource.py, syndicate/core/transform/cloudformation/converter/cf_sqs_converter.py, syndicate/core/transform/terraform/converter/tf_sqs_converter.py
Fixed an error related to SQS FIFO Queue availability regions
=> Fixed an error related to SQS FIFO Queue availability regions

CHANGELOG.md, syndicate/connection/helper.py
Fixed an issue related to deploying SQS Queue with configured redrive_policy
=> Fixed an issue related to deploying SQS Queue with configured DLQ

CHANGELOG.md, syndicate/core/handlers.py
=> force upload option added to assemble commands

CHANGELOG.md, syndicate/connection/s3_connection.py, syndicate/core/handlers.py
Added force_upload action to all assemble commands
=> fix assemble command

.github/workflows/build-and-check-python-package.yml
Updated the twine version to 5.1.1
=> CI: Updated the twine version to 5.1.1

.github/workflows/ci-java.yml, plugin/deployment-configuration-annotations/pom.xml, plugin/deployment-configuration-maven-plugin/pom.xml, plugin/pom.xml
Fixed the 'gpg: signing failed: Inappropriate ioctl for device' issue during publishing to Maven
=> Fixed the 'gpg: signing failed: Inappropriate ioctl for device' issue during publishing to Maven

CHANGELOG.md, syndicate/connection/api_gateway_connection.py, syndicate/core/resources/api_gateway_resource.py
Fixed API Gateway duplication in case of existing API Gateway with the same name
=> Fixed API Gateway duplication in case of existing API Gateway with the same name

CHANGELOG.md, setup.py, syndicate/core/handlers.py
Fix detection of usage `--rollback_on_error` option with an incompatible option `--continue_deploy`
=> Fix detection of usage `--rollback_on_error` option with an incompatible option `--continue_deploy`

syndicate/core/build/deployment_processor.py
Fixed continue deploy related issue
=> Fixed continue deploy related issue

CHANGELOG.md, syndicate/connection/cognito_identity_provider_connection.py, syndicate/core/resources/lambda_resource.py
Added possibility to set up Cognito user pool client ID in lambda function environment variable
=> CUP client id as lambda env variable value

CHANGELOG.md, plugin/deployment-configuration-annotations/pom.xml, plugin/deployment-configuration-annotations/src/main/java/com/syndicate/deployment/annotations/environment/EnvironmentVariable.java, plugin/deployment-configuration-annotations/src/main/java/com/syndicate/deployment/model/LambdaConfiguration.java, plugin/deployment-configuration-annotations/src/main/java/com/syndicate/deployment/model/ResourceType.java, plugin/deployment-configuration-annotations/src/main/java/com/syndicate/deployment/model/environment/ValueTransformer.java, plugin/deployment-configuration-annotations/src/main/java/com/syndicate/deployment/model/terraform/TerraformLambdaConfiguration.java, plugin/deployment-configuration-maven-plugin/pom.xml, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/factories/LambdaConfigurationFactory.java, plugin/deployment-configuration-maven-plugin/src/main/java/com/syndicate/deployment/processor/impl/LambdaHandlerAnnotationProcessor.java, plugin/pom.xml, setup.py, syndicate/core/generators/contents.py
add Cognito ID dynamic resolving support to the Syndicate Java plugin
=> add Cognito ID dynamic resolving support to the Syndicate Java plugin

syndicate/core/build/meta_processor.py, syndicate/core/build/validator/mapping.py
Adjusted resources dependencies description validation
=> Adjusted resources dependencies description validation

CHANGELOG.md, syndicate/core/project_state/project_state.py
=> [EPMCEOOS-6086] Fixed lock resolving issue

.github/workflows/ci-java.yml
* Added the new logic for checking changes in files during the release event in GitHub workflows
=> [cd] added the new logic for checking changes in files during the release event

CHANGELOG.md, setup.py, syndicate/connection/s3_connection.py, syndicate/core/resources/s3_resource.py
- Speed up deletion of s3 bucket with lots of objects
=> Speed up deletion of s3 bucket with lots of objects

CHANGELOG.md, syndicate/core/resources/s3_resource.py
Fixed an issue related to bucket name resolving in the s3_bucket policy
=> Fix bucket name in bucket policy

CHANGELOG.md, syndicate/core/build/meta_processor.py, syndicate/core/generators/deployment_resources/s3_bucket_generator.py, syndicate/core/resources/s3_resource.py
- Fixed deployment failure if resource name is the same as resource type
- Fixed an issue related to resource name resolving if ARN is a list item
=> [EPMCEOOS-6165, EPMCEOOS-6162, EPMCEOOS-6164] Issues with resource name resolving

CHANGELOG.md, setup.py, syndicate/core/build/meta_processor.py
Fixed an issue related to name resolving if one resource name contains another resource name.
=> Fixed an issue related to name resolving if one resource name contains another resource name.

CHANGELOG.md, setup.py, syndicate/core/build/runtime/python.py, syndicate/core/handlers.py, syndicate/core/helper.py
Added enhanced logging of the `build` command execution
=> Added enhanced logging of the `build` command execution

CHANGELOG.md, syndicate/connection/dax_connection.py, syndicate/connection/firehose_connection.py, syndicate/connection/iam_connection.py, syndicate/connection/sns_connection.py, syndicate/core/build/bundle_processor.py, syndicate/core/build/deployment_processor.py, syndicate/core/build/helper.py, syndicate/core/build/meta_processor.py, syndicate/core/build/runtime/nodejs.py, syndicate/core/decorators.py, syndicate/core/handlers.py, syndicate/core/helper.py, syndicate/core/project_state/project_state.py, syndicate/core/resources/api_gateway_resource.py, syndicate/core/resources/batch_jobqueue_resource.py, syndicate/core/resources/dax_resource.py, syndicate/core/resources/firehose_resource.py, syndicate/core/resources/iam_resource.py, syndicate/core/resources/lambda_resource.py
- Improved logging for the deletion of a resource that does not exist in the account
- Fixed Lambda Layer packaging for the NodeJS runtime
- Fixed an issue where newly added resources (after deploy) were causing the update operation to fail
=> Improve deletion log

CHANGELOG.md, syndicate/core/resources/dynamo_db_resource.py
Fixed an issue related to removing CloudWatch alarms that were used for Dynamodb autoscaling
=> [EPMCEOOS-6173] Fixed an issue related to removing CloudWatch alarms

CHANGELOG.md, syndicate/core/build/deployment_processor.py, syndicate/core/resources/cloud_watch_alarm_resource.py, syndicate/core/resources/dynamo_db_resource.py, syndicate/core/resources/ebs_resource.py, syndicate/core/resources/ec2_resource.py, syndicate/core/resources/eventbridge_scheduler_resource.py, syndicate/core/resources/iam_resource.py, syndicate/core/resources/kinesis_resource.py, syndicate/core/resources/lambda_resource.py, syndicate/core/resources/s3_resource.py, syndicate/core/resources/step_functions_resource.py, syndicate/core/resources/swagger_ui_resource.py
Fixed an issue with the absence of lambda's information in the output file in case of failure on the trigger configuring step
=> [EPMCEOOS-6183] Fixed an issue with the absence of lambda's information in the output file in case of failure on the trigger configuring step

CHANGELOG.md, syndicate/core/build/deployment_processor.py, syndicate/core/constants.py, syndicate/core/handlers.py, syndicate/core/helper.py, syndicate/core/project_state/project_state.py
- Fixed an issue related to losing state after partial clean
- Fixed an issue related to the latest output resolving
=> [EPMCEOOS-6184] Fixed an issue related to losing state after partial clean

CHANGELOG.md, syndicate/connection/helper.py, syndicate/core/resources/lambda_resource.py
Fixed an issue related to updating lambda triggers
=> Fixed an issue related to updating lambda triggers

CHANGELOG.md, syndicate/connection/lambda_connection.py
Fixed lambda event source mapping inactivity after deployment
=> Fixed lambda event source mapping inactivity after deployment

CHANGELOG.md, syndicate/core/handlers.py, syndicate/core/project_state/status_processor.py
- Event status added to the command `syndicate status` output
- Added validation for incompatible parameters(`--events`, `--resources`) of the command `syndicate status`
=> Event status added to the command `syndicate status` output

examples/java/demo-apigateway-cognito/.syndicate-config-demo-apigateway-cognito/syndicate_aliases.yml, examples/java/demo-apigateway-cognito/jsrc/main/java/com/demoapigatewaycognito/ApiHandler.java, examples/python/lambda-cognito-api-gateway/src/lambdas/lambda_example/lambda_config.json
Added lambda alias usage to examples with API GW and Cognito
=> Added lambda alias usage to examples with API GW and Cognito

CHANGELOG.md, syndicate/core/build/deployment_processor.py
Improved logging in case of the absence of resources to clean
=> Added log message in case of absence of resources to clean

CHANGELOG.md, setup.py, syndicate/connection/api_gateway_connection.py, syndicate/connection/sns_connection.py, syndicate/core/resources/api_gateway_resource.py
=> OAS v3 Open API Tagging added, sns topic deletion fixed

CHANGELOG.md, syndicate/core/build/runtime/dotnet.py, syndicate/core/generators/lambda_function.py, syndicate/core/resources/lambda_resource.py
Added support lambda layers with runtime DotNet
=> Added support lambda layers with runtime DotNet

CHANGELOG.md, examples/dotnet/lambda-basic/.syndicate-config-lambda-basic/syndicate.yml, examples/dotnet/lambda-basic/.syndicate-config-lambda-basic/syndicate_aliases.yml, examples/dotnet/lambda-basic/deployment_resources.json, examples/dotnet/lambda-basic/dnapp/lambdas/lambda_example/Function.cs, examples/dotnet/lambda-basic/dnapp/lambdas/lambda_example/Function.csproj, examples/dotnet/lambda-basic/dnapp/lambdas/lambda_example/deployment_resources.json, examples/dotnet/lambda-basic/dnapp/lambdas/lambda_example/lambda_config.json
Added an example of a lambda function with runtime dotnet
=> Added an example of a lambda function with runtime dotnet

syndicate/core/generators/contents.py
added a real library to dotnet layer template
=> added real library to dotnet layer template

CHANGELOG.md, syndicate/core/build/deployment_processor.py, syndicate/core/build/runtime/python.py
- Improved error message if errors occur during Python requirements installation
- Changed log level from info to warn if updating of the resource skipped because of absence it in the deployment output
=> Improved error messages

CHANGELOG.md, syndicate/core/project_state/project_state.py
Fixed an issue related to locking the state
=> Fixed an issue related to locking the state

CHANGELOG.md, syndicate/connection/api_gateway_connection.py, syndicate/core/__init__.py, syndicate/core/build/meta_processor.py, syndicate/core/export/configuration_exporter.py, syndicate/core/export/export_processor.py, syndicate/core/handlers.py, syndicate/core/resources/api_gateway_resource.py, syndicate/core/resources/batch_compenv_resource.py, syndicate/core/resources/ec2_resource.py, syndicate/core/resources/resources_provider.py
Add support tags for `OAS V3` as part of the `oas_v3.json` file, using the `x-syndicate-openapi-tags` key
=> Add support tags for `OAS V3` as part of the `oas_v3.json` file

CHANGELOG.md, syndicate/core/constants.py, syndicate/core/decorators.py, syndicate/core/groups/appsync.py, syndicate/core/groups/generate.py, syndicate/core/groups/meta.py, syndicate/core/groups/tags.py, syndicate/core/handlers.py, syndicate/core/helper.py, syndicate/core/project_state/project_state.py
+ new decorator check_bundle_deploy_names_for_existence
=> Fix return code for failed commands

syndicate/core/resources/api_gateway_resource.py
Fixed Python 3.10 f-string compatibility issue
=> fixed python 3.10 f-string compatibility issue

CHANGELOG.md, requirements.txt, setup.py
Unused library `colorama` removed from the requirements
=> Unused library `colorama` removed from the requirements

CHANGELOG.md, syndicate/core/resources/api_gateway_resource.py
Fixed duplication of the API Gateway of type `web_socket_api_gateway` during deployment
=> Fixed duplication of the API Gateway of type `web_socket_api_gateway` during deployment

CHANGELOG.md, setup.py, syndicate/core/handlers.py
Fixed an issue related to modification operations event synchronization
=> Fixed an issue related to modification operations event synchronization

CHANGELOG.md, syndicate/connection/helper.py
Fixed log message duplication during retries
=> Fixed log message duplication during retries

CHANGELOG.md, syndicate/core/resources/api_gateway_resource.py
Fixed issue related to deployment API Gateway defined with OpenAPI spec and documented path `Path Item Object`
=> Fixed issue related to deployment API Gateway defined with OpenAPI spec

CHANGELOG.md, syndicate/core/__init__.py, syndicate/core/build/bundle_processor.py, syndicate/core/build/validator/lambda_validator.py, syndicate/core/handlers.py, syndicate/core/resources/lambda_resource.py
- Fixed `lambda_layer` duplication during deployment.
- Fixed an issue related to deploy target bucket creation
=> Fix `lambda_layer` duplication, fix deploy target bucket creation

CHANGELOG.md, syndicate/core/build/deployment_processor.py
Fixed an issue related to the resource absence in deployment output in case of exception
=> Fixed an issue related to the resource absence in deployment output

CHANGELOG.md, syndicate/core/resources/dax_resource.py
Fixed subnet group deletion during a DAX cluster cleaning
=> Fixed subnet group deletion during a DAX cluster cleaning

CHANGELOG.md, syndicate/core/build/bundle_processor.py, syndicate/core/build/deployment_processor.py, syndicate/core/handlers.py, syndicate/core/helper.py, syndicate/core/project_state/project_state.py, syndicate/core/resources/lambda_resource.py
Changed the resolution flow of the deployment output file flow, so the latest deploy output file is used for commands update, continue deploy, and clean.
=> fixed resolving of latest deployment output
