epam/aws-syndicate

- README.md
Remove space in 
> Linux: Detailed guide how to install Python you can find [here](https://docs.python- guide.org/starting/install3/linux/ "here").
> remove not needed space

- syndicate/connection/api_gateway_connection.py
- syndicate/core/resources/api_gateway_resource.py
**Explain the *details* for making this change. What existing problem does the pull request solve?**
Implementation of #76 
Added the ability to set integration parameters to make API Gateway creation more automatic. Also added docstring in function `create_service_integration`.
An example of declaring integration parameters in deployment_resources.json:
```
{
...
"POST": {
"integration_request_parameters": {
"integration.request.path.name": "method.request.path.username",
"integration.request.querystring.username": "method.request.querystring.username",
"integration.request.header.Content-Type": "'application/x-amz-json-1.1'"
}
}
...
}
```
So, the template for key is `integration.request.{location}.{name}` and for value is `method.request.{location}.{name}`.
The …
> Add abillity to set integration request parameters

- CHANGELOG.md
- syndicate/connection/api_gateway_connection.py
- syndicate/core/build/meta_processor.py
- syndicate/core/resources/api_gateway_resource.py
Related to #79
**Explain the *details* for making this change. What existing problem does the pull request solve?**
Added the ability to create request validation for API Gateway via deployment_resources.json.
Here is the example of declaring integration parameters in deployment_resources.json:
```
...
"request_validator": {
"name": "${validator_name},
"validate_request_body": true|false,
"validate_request_parameters": true|false
},
...
```
The name of the validator is optional. If no name is specified, it will match what Amazon sets by default (`Validate body`, `Validate query string parameters and headers` or `Validate body, query string parameters, and headers`).
The parameters `validate_request_body` and `validate_request_parameters` are false by default. 
The …
> Add request validator

- .travis.yml
- CHANGELOG.md
Related to #85 
All of the Travis builds fail due to the deprecated version of Java used for SonarQube Scanner.
SonarQube Scanner now runs on Java 11, Maven tests still runs on Java 8.
Builds run successfully:
> Update Java version in Travis builds

- CHANGELOG.md
- syndicate/core/handlers.py
The account_id parameter must be of type str for correct saving in yml files
`closes #86`
> #86 fix incorrect account id storing

- syndicate/core/resources/api_gateway_resource.py
Add missing PATCH method in the list of supported HTTP methods for API Gateway.
After that, aws-syndicate successfully deploys IG resources with PATCH methods.
> add missing PATCH method to list of supported methods

- syndicate/connection/api_gateway_connection.py
- syndicate/core/resources/api_gateway_resource.py
To enable payload compression for API GW - add "minimum_compression_size" param to api_gateway resource inside deployment_resouces.json and assign the value according to API GW requirements, beginning with 0 and up till 10485760 (10M).
> Api gw compression

- syndicate/core/generators/__init__.py
Error in `_re_survey()`:
- if user input is not `n` or `y` - returns `True` (overwrite)
```python
def _re_survey(answer, project_path):
while answer not in ('y', 'n'):
answer = input('Please enter [y/n] value: ')
if answer == 'y':
os.makedirs(project_path, exist_ok=True)
return True
elif answer == 'n':
return False
return True
```
Replaced with
```python
def _re_survey(answer, project_path):
while True:
if answer == 'y':
os.makedirs(project_path, exist_ok=True)
return True
elif answer == 'n':
return False
answer = input('Please enter [y/n] value: ').lower()
```
closes #138
> Syndicate overrides existing lambda even after user forbids to do that in a prompt.

- syndicate/core/helper.py
Bundle names must only contain letters, numbers and ‘-_.’ with total bundle name length up to 64 characters.
Closes #134
> [Improvement] Add validation of bundle_names

- syndicate/core/handlers.py
- syndicate/core/helper.py
Created callback that combines both resolving of latest bundle name (if not provided) and validation that bundle exists
In case of no bundles available for the project, exception with readable reason will be thrown:
closes #157
> Fix upload NoneType error on `syndicate upload` when there's no bundles available

- syndicate/core/conf/generator.py
Add missing `account_id` and `region` aliases in `syndicate_aliases.yml` generated with `syndicate generate config` command
> add missing aliases

- syndicate/core/handlers.py
- syndicate/core/project_state/project_state.py
- syndicate/core/project_state/sync_processor.py
Changed the main function under 'syndicate sync' so that it also could compare and sync 'latest_deploy' property. So now if local .syndicate doesn't have 'latest_deploy' but the remote one does, the remove 'latest_deploy' will be pulled. **Important:** since the Syndicate make project state sync before and after most of actions (deploy, clean), there was a situation when: 
syndicate synced -> syndicate cleaned resources and put local latest deploy empty -> syndicate synced (hence pulled the remove latest_deploy which still existed despite cleaning). To avoid this I added erasing 'latest_deploy' from the remote .syndicate along with erasing the local one.
> Fix clean issues

- syndicate/connection/iam_connection.py
- syndicate/core/constants.py
- syndicate/core/handlers.py
- syndicate/core/helper.py
- syndicate/core/project_state/project_state.py
* fix the bug when the Syndicate threw an error if permission boundary is not set;
* add resolving latest bundle_name also from possible 'package_meta' action, not only from 'build';
* remove sorting from __save_events method. Now each new event is just inserted by the zero index. During 'syndicate sync' the events from bucket are compared with local ones and inserted to their places keeping the right order.
* put some consts together
> Resolve bundle name from package meta

- syndicate/core/__init__.py
* If you wanted to use `AWS_PROFILE` env variable to choose a specific credentials from `.aws/credentials` you could face an issue  when the Syndicate didn't allow to assume a role of use temp credentials based on the profile in case 'syndicate.yaml' didn't have keys itself. But obviously you don't have to keep keys in `syndicate.yaml` if you consider setting `AWS_PROFILE` so I removed some checks.
* Removed prompt whether to generate .syndicate when it doesn't exist due to the discussion and difficulties in pipelines
> Simplify checking whether to assume the role or use temp creds

- syndicate/core/__init__.py
- syndicate/core/build/bundle_processor.py
- syndicate/core/conf/bucket_view.py
- syndicate/core/conf/processor.py
- syndicate/core/decorators.py
- syndicate/core/project_state/project_state.py
- syndicate/core/project_state/sync_processor.py
- syndicate/core/resources/ebs_resource.py
- syndicate/core/resources/lambda_resource.py
The request, contains changes, which alter the following behavior.
**Deploy Target Bucket**
When one wishes to use S3 URI, they are free to manually provide the respective value to the yaml config. The backward compatibility is satisfied by wrapping the raw the config value into a concrete `AbstractBucketView` instance, having previously composed a concrete parser class of `AbstractViewDigest` type, into the view-instance, which is presigned as the `deploy_target_bucket_view` property of the  `ConfigHolder`. The latter class, apart from the `deploy_target_bucket` property, serving as a name of the bucket, also provides the compound key / object path data, by invoking the `deploy_target_bucket_key_compound` property. Currently each use-case, which had been only prescribed to the _name_ …
> S3 URI Compatibility Adaptation

- syndicate/core/build/runtime/nodejs.py
*The issue was:* if a user has nodejs lambda with dependencies in there, the first 'syndicate assemble' worked properly but left some artifacts in root lambda's folder:
Then during the second build 'npm install' threw us an error about some unexpected files:
After generating nodejs lambda its 'package.json' file contains 'name: {lambda_name}' which is also the root lambda's folder. It seems to me, due to this peculiarity 'npm install --prefix {root}' command inside nodejs build function confused a bit and installed packages wrongly. 
The commit seems to correct the issue.
> Fix an issue with redundant files in nodejs assemble

- CHANGELOG.md
- setup.py
- syndicate/connection/lambda_connection.py
- syndicate/core/build/validator/lambda_validator.py
- syndicate/core/resources/lambda_resource.py
Lambda parameter `architecture` changed to `architectures`, and the value of the key changed to a list of string
> Lambda parameter `architecture` changed to `architectures`

- CHANGELOG.md
- syndicate/core/build/artifact_processor.py
- syndicate/core/build/meta_processor.py
- syndicate/core/handlers.py
Deprecated Lambda runtime Java8
Added support of Lambda runtime Java17 and Java21
> Deprecate java8 lambdas runtime

- syndicate/connection/s3_connection.py
Fixed wrong tabulation which could lead to ignoring s3 triggers configured for lambdas which had no filter rules attribute.
> fix tabulation

- CHANGELOG.md
- setup.py
- syndicate/core/build/bundle_processor.py
- syndicate/core/build/deployment_processor.py
- syndicate/core/constants.py
- syndicate/core/handlers.py
- syndicate/core/helper.py
- syndicate/core/project_state/project_state.py
- The key `operation_status` in `latest_deploy` section of the syndicate state file(.syndicate) renamed to `is_succeeded`
- Changed deployment flow to work despite the latest deployment failed
- Changed deployment flow with the flag `--continue_deploy` to work despite the latest deployment being absent or succeeded
- Implemented rolling back on error mechanism(flag `--rollback_on_error`) for deployment flow with the flag `--continue_deploy`
- Added confirmation request mechanism for the `update` command in case the latest deployment failed
- Added the flag `--force` for the `update` command to run an update without confirmation request in case the latest deployment failed
- Added proper messages for commands `update` and `clean` if deployed resources are absent(output file not found)
> [EPMCEOOS-6079] Feature/improve deploy continue deploy

- CHANGELOG.md
- setup.py
- syndicate/core/build/bundle_processor.py
- syndicate/core/build/deployment_processor.py
- syndicate/core/handlers.py
- syndicate/core/helper.py
- syndicate/core/resources/base_resource.py
- syndicate/core/resources/lambda_resource.py
- Added logging of resource names that cause errors to improve error diagnostics
- Fix the resource update issue that occurs when a deploy_name is specified by user (not default one) but deployment 
output for the latest deployment is empty
- Fixed an issue where updating only certain resources caused the deployment output to be overwritten with only these 
resources, instead of updating the existing meta
> Resource name in error logs

- CHANGELOG.md
- syndicate/core/resources/lambda_resource.py
Fixed an issue when a lambda deployment fails when a trigger defined in meta does not exist
> Add check for lambda trigger existence before creation

- CHANGELOG.md
- syndicate/core/generators/lambda_function.py
Fixed silent overwriting existing lambda with runtime Java during the command `syndicate generate lambda`
> Fixed silent overwriting lambda with runtime Java

- CHANGELOG.md
- setup.py
- syndicate/core/build/artifact_processor.py
- syndicate/core/build/runtime/dotnet.py
- syndicate/core/build/runtime/java.py
- syndicate/core/build/runtime/nodejs.py
- syndicate/core/build/runtime/python.py
- syndicate/core/build/runtime/swagger_ui.py
- syndicate/core/handlers.py
- Added `--skip_tests` option to `build`, `test` and `assemble_java_mvn` commands to not run tests during or after 
building the bundle
- Added `--errors_allowed` option to `assemble_python` and `assemble` commands
- Improved logic of option `--errors_allowed` to allow dependency installing if it is not possible to find a 
requirement that fits a specific platform. In this case, the dependencies will be installed independently 
of each other or without specifying a specific platform (using default platform `any`). Python-specific feature
> Improve --errors_allowed option and add --skip_tests

- CHANGELOG.md
- syndicate/core/build/bundle_processor.py
- syndicate/core/build/deployment_processor.py
Fix the behavior of the `deploy` command when the latest output file/folder is missing
> Fix the behavior of the `deploy` command when the latest output is absent

- CHANGELOG.md
- syndicate/core/resources/lambda_resource.py
Fix `clean` command for `output` folder to correctly resolve ARN for Lambda and properly process and remove the `outputs` folder if Lambda is part of the deployment
> Fix `clean` command for `output` folder

- CHANGELOG.md
- setup.py
- syndicate/core/build/artifact_processor.py
- syndicate/core/build/bundle_processor.py
- syndicate/core/build/validator/lambda_validator.py
- syndicate/core/handlers.py
- syndicate/core/resources/lambda_resource.py
- Changed `--force_upload` parameter type for assemble commands from `string` to `flag`
- Fixed logic of `--force_upload` flag in assemble commands
- Added `--force_upload` flag to `assemble_appsync` and `assemble_swagger_ui` commands
- Fixed issue if the last deploy output file was deleted from the s3 bucket, and it would result that lambda 
triggers not being able to update
> Fix force upload
